/**
 * @module go-source-builder
 *
 * Simple string builder for generating Go source files.
 * Produces well-structured Go code without needing an AST library.
 */

export interface GoStructField {
  name: string
  type: string
  jsonTag: string
  comment?: string
}

export class GoSourceBuilder {
  private lines: string[] = []

  addGeneratedHeader(): this {
    this.lines.push("// Code generated by tg-bot-sdk codegen. DO NOT EDIT.")
    this.lines.push("")
    return this
  }

  addPackage(name: string): this {
    this.lines.push(`package ${name}`)
    this.lines.push("")
    return this
  }

  addImport(...imports: string[]): this {
    if (imports.length === 0) return this
    if (imports.length === 1) {
      this.lines.push(`import "${imports[0]}"`)
    } else {
      this.lines.push("import (")
      for (const imp of imports) {
        this.lines.push(`\t"${imp}"`)
      }
      this.lines.push(")")
    }
    this.lines.push("")
    return this
  }

  addComment(lines: string[]): this {
    for (const line of lines) {
      // Split on actual newlines and comment each sub-line
      for (const subLine of line.split("\n")) {
        const trimmed = subLine.trim()
        if (trimmed.length === 0) continue
        this.lines.push(`// ${trimmed}`)
      }
    }
    return this
  }

  addStruct(name: string, fields: GoStructField[], comment?: string[]): this {
    if (comment && comment.length > 0) {
      this.addComment([`${name} — ${comment[0]}`, ...comment.slice(1)])
    }
    this.lines.push(`type ${name} struct {`)
    for (const field of fields) {
      const tag = "`" + `json:"${field.jsonTag}"` + "`"
      if (field.comment) {
        this.lines.push(`\t// ${field.comment}`)
      }
      this.lines.push(`\t${field.name} ${field.type} ${tag}`)
    }
    this.lines.push("}")
    this.lines.push("")
    return this
  }

  addEmptyStruct(name: string, comment?: string[]): this {
    if (comment && comment.length > 0) {
      this.addComment([`${name} — ${comment[0]}`, ...comment.slice(1)])
    }
    this.lines.push(`type ${name} struct{}`)
    this.lines.push("")
    return this
  }

  addInterface(name: string, markerMethod: string, comment?: string[]): this {
    if (comment && comment.length > 0) {
      this.addComment([`${name} — ${comment[0]}`, ...comment.slice(1)])
    }
    this.lines.push(`type ${name} interface {`)
    this.lines.push(`\t${markerMethod}()`)
    this.lines.push("}")
    this.lines.push("")
    return this
  }

  addMarkerImpl(typeName: string, markerMethod: string): this {
    this.lines.push(`func (${typeName}) ${markerMethod}() {}`)
    return this
  }

  addTypeAlias(name: string, target: string, comment?: string[]): this {
    if (comment && comment.length > 0) {
      this.addComment([`${name} — ${comment[0]}`, ...comment.slice(1)])
    }
    this.lines.push(`type ${name} = ${target}`)
    this.lines.push("")
    return this
  }

  addVar(name: string, value: string): this {
    this.lines.push(`var ${name} = ${value}`)
    return this
  }

  addFunc(
    receiver: string | undefined,
    name: string,
    params: string,
    returns: string,
    bodyLines: string[]
  ): this {
    const rcv = receiver ? `(${receiver}) ` : ""
    this.lines.push(`func ${rcv}${name}(${params}) ${returns} {`)
    for (const line of bodyLines) {
      this.lines.push(`\t${line}`)
    }
    this.lines.push("}")
    this.lines.push("")
    return this
  }

  addRaw(line: string): this {
    this.lines.push(line)
    return this
  }

  addBlankLine(): this {
    this.lines.push("")
    return this
  }

  toString(): string {
    return this.lines.join("\n") + "\n"
  }
}
