// Code generated by tg-bot-sdk codegen. DO NOT EDIT.

package tgapi

import (
	"encoding/json"
	"fmt"
)

func unmarshalBackgroundFill(data []byte) (BackgroundFill, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "solid":
		var v BackgroundFillSolid
		return &v, json.Unmarshal(data, &v)
	case "gradient":
		var v BackgroundFillGradient
		return &v, json.Unmarshal(data, &v)
	case "freeform_gradient":
		var v BackgroundFillFreeformGradient
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown BackgroundFill type: %q", disc.Type)
	}
}

func unmarshalBackgroundType(data []byte) (BackgroundType, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "fill":
		var v BackgroundTypeFill
		return &v, json.Unmarshal(data, &v)
	case "wallpaper":
		var v BackgroundTypeWallpaper
		return &v, json.Unmarshal(data, &v)
	case "pattern":
		var v BackgroundTypePattern
		return &v, json.Unmarshal(data, &v)
	case "chat_theme":
		var v BackgroundTypeChatTheme
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown BackgroundType type: %q", disc.Type)
	}
}

func unmarshalBotCommandScope(data []byte) (BotCommandScope, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "default":
		var v BotCommandScopeDefault
		return &v, json.Unmarshal(data, &v)
	case "all_private_chats":
		var v BotCommandScopeAllPrivateChats
		return &v, json.Unmarshal(data, &v)
	case "all_group_chats":
		var v BotCommandScopeAllGroupChats
		return &v, json.Unmarshal(data, &v)
	case "all_chat_administrators":
		var v BotCommandScopeAllChatAdministrators
		return &v, json.Unmarshal(data, &v)
	case "chat":
		var v BotCommandScopeChat
		return &v, json.Unmarshal(data, &v)
	case "chat_administrators":
		var v BotCommandScopeChatAdministrators
		return &v, json.Unmarshal(data, &v)
	case "chat_member":
		var v BotCommandScopeChatMember
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown BotCommandScope type: %q", disc.Type)
	}
}

func unmarshalChatBoostSource(data []byte) (ChatBoostSource, error) {
	var disc struct {
		Source string `json:"source"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Source {
	case "premium":
		var v ChatBoostSourcePremium
		return &v, json.Unmarshal(data, &v)
	case "gift_code":
		var v ChatBoostSourceGiftCode
		return &v, json.Unmarshal(data, &v)
	case "giveaway":
		var v ChatBoostSourceGiveaway
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown ChatBoostSource source: %q", disc.Source)
	}
}

func unmarshalChatMember(data []byte) (ChatMember, error) {
	var disc struct {
		Status string `json:"status"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Status {
	case "creator":
		var v ChatMemberOwner
		return &v, json.Unmarshal(data, &v)
	case "administrator":
		var v ChatMemberAdministrator
		return &v, json.Unmarshal(data, &v)
	case "member":
		var v ChatMemberMember
		return &v, json.Unmarshal(data, &v)
	case "restricted":
		var v ChatMemberRestricted
		return &v, json.Unmarshal(data, &v)
	case "left":
		var v ChatMemberLeft
		return &v, json.Unmarshal(data, &v)
	case "kicked":
		var v ChatMemberBanned
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown ChatMember status: %q", disc.Status)
	}
}

func unmarshalInputMedia(data []byte) (InputMedia, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "animation":
		var v InputMediaAnimation
		return &v, json.Unmarshal(data, &v)
	case "document":
		var v InputMediaDocument
		return &v, json.Unmarshal(data, &v)
	case "audio":
		var v InputMediaAudio
		return &v, json.Unmarshal(data, &v)
	case "photo":
		var v InputMediaPhoto
		return &v, json.Unmarshal(data, &v)
	case "video":
		var v InputMediaVideo
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown InputMedia type: %q", disc.Type)
	}
}

func unmarshalInputPaidMedia(data []byte) (InputPaidMedia, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "photo":
		var v InputPaidMediaPhoto
		return &v, json.Unmarshal(data, &v)
	case "video":
		var v InputPaidMediaVideo
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown InputPaidMedia type: %q", disc.Type)
	}
}

func unmarshalInputProfilePhoto(data []byte) (InputProfilePhoto, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "static":
		var v InputProfilePhotoStatic
		return &v, json.Unmarshal(data, &v)
	case "animated":
		var v InputProfilePhotoAnimated
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown InputProfilePhoto type: %q", disc.Type)
	}
}

func unmarshalInputStoryContent(data []byte) (InputStoryContent, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "photo":
		var v InputStoryContentPhoto
		return &v, json.Unmarshal(data, &v)
	case "video":
		var v InputStoryContentVideo
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown InputStoryContent type: %q", disc.Type)
	}
}

func unmarshalMenuButton(data []byte) (MenuButton, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "commands":
		var v MenuButtonCommands
		return &v, json.Unmarshal(data, &v)
	case "web_app":
		var v MenuButtonWebApp
		return &v, json.Unmarshal(data, &v)
	case "default":
		var v MenuButtonDefault
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown MenuButton type: %q", disc.Type)
	}
}

func unmarshalMessageOrigin(data []byte) (MessageOrigin, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "user":
		var v MessageOriginUser
		return &v, json.Unmarshal(data, &v)
	case "hidden_user":
		var v MessageOriginHiddenUser
		return &v, json.Unmarshal(data, &v)
	case "chat":
		var v MessageOriginChat
		return &v, json.Unmarshal(data, &v)
	case "channel":
		var v MessageOriginChannel
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown MessageOrigin type: %q", disc.Type)
	}
}

func unmarshalOwnedGift(data []byte) (OwnedGift, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "regular":
		var v OwnedGiftRegular
		return &v, json.Unmarshal(data, &v)
	case "unique":
		var v OwnedGiftUnique
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown OwnedGift type: %q", disc.Type)
	}
}

func unmarshalPaidMedia(data []byte) (PaidMedia, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "preview":
		var v PaidMediaPreview
		return &v, json.Unmarshal(data, &v)
	case "photo":
		var v PaidMediaPhoto
		return &v, json.Unmarshal(data, &v)
	case "video":
		var v PaidMediaVideo
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown PaidMedia type: %q", disc.Type)
	}
}

func unmarshalPassportElementError(data []byte) (PassportElementError, error) {
	var disc struct {
		Source string `json:"source"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Source {
	case "data":
		var v PassportElementErrorDataField
		return &v, json.Unmarshal(data, &v)
	case "front_side":
		var v PassportElementErrorFrontSide
		return &v, json.Unmarshal(data, &v)
	case "reverse_side":
		var v PassportElementErrorReverseSide
		return &v, json.Unmarshal(data, &v)
	case "selfie":
		var v PassportElementErrorSelfie
		return &v, json.Unmarshal(data, &v)
	case "file":
		var v PassportElementErrorFile
		return &v, json.Unmarshal(data, &v)
	case "files":
		var v PassportElementErrorFiles
		return &v, json.Unmarshal(data, &v)
	case "translation_file":
		var v PassportElementErrorTranslationFile
		return &v, json.Unmarshal(data, &v)
	case "translation_files":
		var v PassportElementErrorTranslationFiles
		return &v, json.Unmarshal(data, &v)
	case "unspecified":
		var v PassportElementErrorUnspecified
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown PassportElementError source: %q", disc.Source)
	}
}

func unmarshalReactionType(data []byte) (ReactionType, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "emoji":
		var v ReactionTypeEmoji
		return &v, json.Unmarshal(data, &v)
	case "custom_emoji":
		var v ReactionTypeCustomEmoji
		return &v, json.Unmarshal(data, &v)
	case "paid":
		var v ReactionTypePaid
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown ReactionType type: %q", disc.Type)
	}
}

func unmarshalRevenueWithdrawalState(data []byte) (RevenueWithdrawalState, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "pending":
		var v RevenueWithdrawalStatePending
		return &v, json.Unmarshal(data, &v)
	case "succeeded":
		var v RevenueWithdrawalStateSucceeded
		return &v, json.Unmarshal(data, &v)
	case "failed":
		var v RevenueWithdrawalStateFailed
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown RevenueWithdrawalState type: %q", disc.Type)
	}
}

func unmarshalStoryAreaType(data []byte) (StoryAreaType, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "location":
		var v StoryAreaTypeLocation
		return &v, json.Unmarshal(data, &v)
	case "suggested_reaction":
		var v StoryAreaTypeSuggestedReaction
		return &v, json.Unmarshal(data, &v)
	case "link":
		var v StoryAreaTypeLink
		return &v, json.Unmarshal(data, &v)
	case "weather":
		var v StoryAreaTypeWeather
		return &v, json.Unmarshal(data, &v)
	case "unique_gift":
		var v StoryAreaTypeUniqueGift
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown StoryAreaType type: %q", disc.Type)
	}
}

func unmarshalTransactionPartner(data []byte) (TransactionPartner, error) {
	var disc struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return nil, err
	}
	switch disc.Type {
	case "user":
		var v TransactionPartnerUser
		return &v, json.Unmarshal(data, &v)
	case "chat":
		var v TransactionPartnerChat
		return &v, json.Unmarshal(data, &v)
	case "affiliate_program":
		var v TransactionPartnerAffiliateProgram
		return &v, json.Unmarshal(data, &v)
	case "fragment":
		var v TransactionPartnerFragment
		return &v, json.Unmarshal(data, &v)
	case "telegram_ads":
		var v TransactionPartnerTelegramAds
		return &v, json.Unmarshal(data, &v)
	case "telegram_api":
		var v TransactionPartnerTelegramApi
		return &v, json.Unmarshal(data, &v)
	case "other":
		var v TransactionPartnerOther
		return &v, json.Unmarshal(data, &v)
	default:
		return nil, fmt.Errorf("unknown TransactionPartner type: %q", disc.Type)
	}
}

